[versions]
kotlin = "2.4.20"
changelog = "2.5.0"
junit4 = "4.13.2"

[libraries]
kotlin-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
junit4 = { module = "junit:junit", version.ref = "junit4" }

[plugins]
changelog = { id = "org.jetbrains.changelog", version.ref = "changelog" }
